# Generated by Django 5.2.1 on 2025-10-12 13:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Untitled Project', max_length=255)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('kml_file', models.FileField(blank=True, null=True, upload_to='kml_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project_name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='ProjectArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('area_type', models.CharField(choices=[('uc', 'Union Council'), ('custom', 'Custom Drawn'), ('kml', 'KML Uploaded')], max_length=10)),
                ('selected_city', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_geometry', models.JSONField(blank=True, null=True)),
                ('kml_file', models.FileField(blank=True, null=True, upload_to='kml_files/')),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='urbananalytics.project')),
            ],
        ),
        migrations.CreateModel(
            name='MapState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_layer', models.CharField(blank=True, choices=[('ndvi', 'NDVI'), ('thermal', 'Thermal'), ('aqi', 'AQI')], max_length=20, null=True)),
                ('toggle_state', models.JSONField(default=dict)),
                ('zoom_level', models.FloatField(blank=True, null=True)),
                ('center_coords', models.JSONField(blank=True, null=True)),
                ('basemap_style', models.CharField(default='streets', max_length=50)),
                ('project_area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_state', to='urbananalytics.projectarea')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('ndvi', 'NDVI'), ('thermal', 'Thermal'), ('aqi', 'AQI')], max_length=20)),
                ('report_type', models.CharField(choices=[('average', 'Average'), ('pixelwise', 'Pixelwise'), ('1yr_average', '1-Year Average'), ('1yr_pixelwise', '1-Year Pixelwise'), ('2yr_comparison', '2-Year Comparison')], max_length=30)),
                ('area_type', models.CharField(choices=[('uc', 'UC'), ('kml', 'KML')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file', models.FileField(upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urbananalytics.project')),
            ],
        ),
        migrations.CreateModel(
            name='UnionCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('uc_name', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'unique_together': {('city_name', 'uc_name')},
            },
        ),
        migrations.AddField(
            model_name='projectarea',
            name='uc_ids',
            field=models.ManyToManyField(blank=True, to='urbananalytics.unioncouncil'),
        ),
        migrations.CreateModel(
            name='BeforeAfterPixelwise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('area_type', models.CharField(max_length=20)),
                ('uc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('before_year', models.IntegerField()),
                ('after_year', models.IntegerField()),
                ('map_layer_before_path', models.CharField(max_length=500)),
                ('map_layer_after_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urbananalytics.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'analysis_type', 'before_year', 'after_year'], name='urbananalyt_project_26906e_idx'), models.Index(fields=['area_type'], name='urbananalyt_area_ty_9d3438_idx')],
                'unique_together': {('project', 'analysis_type', 'area_type', 'uc_name', 'before_year', 'after_year')},
            },
        ),
        migrations.CreateModel(
            name='BeforeAfterAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('area_type', models.CharField(max_length=20)),
                ('uc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('before_year', models.IntegerField()),
                ('after_year', models.IntegerField()),
                ('stats_before', models.JSONField(blank=True, null=True)),
                ('stats_after', models.JSONField(blank=True, null=True)),
                ('comparison', models.JSONField(blank=True, null=True)),
                ('tile_url_template_before', models.CharField(blank=True, max_length=500, null=True)),
                ('tile_url_template_after', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_after_analyses', to='urbananalytics.project')),
            ],
            options={
                'unique_together': {('project', 'analysis_type', 'area_type', 'uc_name', 'before_year', 'after_year')},
            },
        ),
        migrations.CreateModel(
            name='AreaAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('area_type', models.CharField(max_length=20)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, null=True)),
                ('tile_url_template', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_pixelwise', models.BooleanField(default=False)),
                ('uc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='urbananalytics.project')),
            ],
            options={
                'ordering': ['uc_name', 'start_date'],
                'unique_together': {('project', 'analysis_type', 'start_date', 'end_date', 'area_type', 'uc_name')},
            },
        ),
        migrations.CreateModel(
            name='YearlyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('area_type', models.CharField(max_length=20)),
                ('uc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stats', models.JSONField(blank=True, null=True)),
                ('is_pixelwise', models.BooleanField(default=False)),
                ('tile_url_template', models.CharField(blank=True, max_length=500, null=True)),
                ('map_layer', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_analyses', to='urbananalytics.project')),
            ],
            options={
                'unique_together': {('project', 'analysis_type', 'year', 'area_type', 'uc_name', 'is_pixelwise')},
            },
        ),
        migrations.CreateModel(
            name='YearlyPixelValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('pixel_value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yearly_pixel_values', to='urbananalytics.project')),
            ],
            options={
                'unique_together': {('project', 'analysis_type', 'year', 'lat', 'lng')},
            },
        ),
    ]
