# Generated by Django 5.2.1 on 2025-09-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beforeaftercomparison',
            name='class_area_after',
        ),
        migrations.RemoveField(
            model_name='beforeaftercomparison',
            name='class_area_before',
        ),
        migrations.RemoveField(
            model_name='beforeaftercomparison',
            name='total_area_after',
        ),
        migrations.RemoveField(
            model_name='beforeaftercomparison',
            name='total_area_before',
        ),
        migrations.RemoveField(
            model_name='yearlyanalysis',
            name='class_area',
        ),
        migrations.RemoveField(
            model_name='yearlyanalysis',
            name='total_area',
        ),
        migrations.AlterField(
            model_name='beforeaftercomparison',
            name='results',
            field=models.JSONField(),
        ),
    ]
