# Generated by Django 5.2.1 on 2025-10-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='reports/'),
        ),
    ]
