# Generated by Django 5.2.1 on 2025-09-25 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearlycomparisonanalysis',
            name='avg_prev_mean',
        ),
        migrations.RemoveField(
            model_name='yearlycomparisonanalysis',
            name='baseline_mean',
        ),
        migrations.RemoveField(
            model_name='yearlycomparisonanalysis',
            name='status',
        ),
        migrations.AddField(
            model_name='areaanalysis',
            name='is_pixelwise',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='areaanalysis',
            name='stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='YearlyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('area_type', models.CharField(max_length=20)),
                ('uc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stats', models.JSONField(blank=True, null=True)),
                ('is_pixelwise', models.BooleanField(default=False)),
                ('map_layer_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_analyses', to='urbananalytics.project')),
            ],
            options={
                'unique_together': {('project', 'analysis_type', 'year', 'area_type', 'uc_name', 'is_pixelwise')},
            },
        ),
        migrations.CreateModel(
            name='YearlyPixelValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('pixel_value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yearly_pixel_values', to='urbananalytics.project')),
            ],
            options={
                'unique_together': {('project', 'analysis_type', 'year', 'lat', 'lng')},
            },
        ),
    ]
