# Generated by Django 5.2.1 on 2025-09-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaanalysis',
            name='stats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
