# Generated by Django 5.2.1 on 2025-09-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='areaanalysis',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='areaanalysis',
            name='city_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='areaanalysis',
            name='uc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='areaanalysis',
            unique_together={('project', 'analysis_type', 'start_date', 'end_date', 'area_type', 'uc_name')},
        ),
    ]
