# Generated by Django 5.2.1 on 2025-09-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0002_remove_beforeaftercomparison_class_area_after_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='yearlyanalysis',
            unique_together={('project', 'analysis_type', 'year', 'area_type', 'uc_name', 'is_pixelwise')},
        ),
        migrations.AddField(
            model_name='beforeaftercomparison',
            name='class_area_after',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='beforeaftercomparison',
            name='class_area_before',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='beforeaftercomparison',
            name='total_area_after',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='beforeaftercomparison',
            name='total_area_before',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='yearlyanalysis',
            name='map_layer_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='beforeaftercomparison',
            name='results',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='yearlyanalysis',
            name='city_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='yearlyanalysis',
            name='stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yearlyanalysis',
            name='uc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='yearlyanalysis',
            name='map_layer',
        ),
        migrations.RemoveField(
            model_name='yearlyanalysis',
            name='mode',
        ),
    ]
