# Generated by Django 5.2.1 on 2025-09-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0002_alter_areaanalysis_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaanalysis',
            name='map_layer_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
