# Generated by Django 5.2.7 on 2025-10-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0002_report_after_year_report_before_year_report_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
