# Generated by Django 5.2.1 on 2025-09-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0002_alter_areaanalysis_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaanalysis',
            name='is_pixelwise',
            field=models.BooleanField(default=False),
        ),
    ]
