# Generated by Django 5.2.1 on 2025-09-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0003_alter_yearlyanalysis_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('area_type', models.CharField(max_length=20)),
                ('before_year', models.IntegerField()),
                ('after_year', models.IntegerField()),
                ('change_stats', models.JSONField()),
                ('map_layer_change', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyze_changes', to='urbananalytics.project')),
            ],
            options={
                'unique_together': {('project', 'analysis_type', 'area_type', 'before_year', 'after_year')},
            },
        ),
    ]
