# Generated by Django 5.2.1 on 2025-09-16 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0003_alter_areaanalysis_map_layer_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyComparisonAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('area_type', models.CharField(max_length=20)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('baseline_year', models.IntegerField()),
                ('comparison_years', models.JSONField()),
                ('baseline_mean', models.FloatField(blank=True, null=True)),
                ('avg_prev_mean', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease'), ('no_change', 'No Change'), ('no_data', 'No Data')], max_length=20)),
                ('stats', models.JSONField(blank=True, null=True)),
                ('map_layer_path', models.FilePathField(blank=True, null=True, path='media/yearly_comparison_layers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_comparisons', to='urbananalytics.project')),
            ],
            options={
                'unique_together': {('project', 'analysis_type', 'baseline_year', 'area_type', 'uc_name')},
            },
        ),
    ]
