# Generated by Django 5.2.7 on 2025-10-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0003_alter_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='reports/'),
        ),
    ]
