# Generated by Django 5.2.1 on 2025-09-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0003_areaanalysis_is_pixelwise'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('area_type', models.CharField(max_length=20)),
                ('uc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stats', models.JSONField(blank=True, null=True)),
                ('is_pixelwise', models.BooleanField(default=False)),
                ('map_layer_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_analyses', to='urbananalytics.project')),
            ],
            options={
                'unique_together': {('project', 'analysis_type', 'year', 'area_type', 'uc_name')},
            },
        ),
        migrations.DeleteModel(
            name='YearlyComparisonAnalysis',
        ),
    ]
