# Generated by Django 5.2.1 on 2025-10-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0004_alter_report_file'),
    ]

    operations = [
    ]
