# Generated by Django 5.2.1 on 2025-09-28 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0004_analyzechange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzechange',
            name='change_stats',
        ),
        migrations.AddField(
            model_name='analyzechange',
            name='map_layer_after',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyzechange',
            name='map_layer_before',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analyzechange',
            name='stats',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='analyzechange',
            name='map_layer_change',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analyzechange',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_analyses', to='urbananalytics.project'),
        ),
    ]
