# Generated by Django 5.2.1 on 2025-09-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0004_yearlycomparisonanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlycomparisonanalysis',
            name='map_layer_path',
            field=models.FilePathField(blank=True, max_length=500, null=True, path='media/yearly_comparison_layers/'),
        ),
    ]
