# Generated by Django 5.2.1 on 2025-09-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0004_yearlyanalysis_delete_yearlycomparisonanalysis'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='yearlyanalysis',
            unique_together={('project', 'analysis_type', 'year', 'area_type', 'uc_name', 'is_pixelwise')},
        ),
    ]
