# Generated by Django 5.2.1 on 2025-09-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0005_remove_analyzechange_change_stats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzechange',
            name='map_layer_after',
        ),
        migrations.RemoveField(
            model_name='analyzechange',
            name='map_layer_before',
        ),
        migrations.RemoveField(
            model_name='analyzechange',
            name='map_layer_change',
        ),
    ]
