# Generated by Django 5.2.1 on 2025-09-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0005_alter_yearlyanalysis_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyPixelValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('analysis_type', 'year', 'lat', 'lng')},
            },
        ),
    ]
