# Generated by Django 5.2.1 on 2025-10-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0005_auto_20251024_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaanalysis',
            name='kml_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
