# Generated by Django 5.2.1 on 2025-09-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0006_remove_analyzechange_map_layer_after_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeforeAfterComparison',
        ),
    ]
