# Generated by Django 5.2.1 on 2025-10-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0006_areaanalysis_kml_hash'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='areaanalysis',
            unique_together={('project', 'analysis_type', 'start_date', 'end_date', 'area_type', 'uc_name', 'kml_hash')},
        ),
    ]
