# Generated by Django 5.2.1 on 2025-09-24 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0006_yearlypixelvalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearlypixelvalue',
            old_name='value',
            new_name='pixel_value',
        ),
        migrations.AlterUniqueTogether(
            name='yearlypixelvalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='yearlypixelvalue',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yearly_pixel_values', to='urbananalytics.project'),
        ),
        migrations.AlterUniqueTogether(
            name='yearlypixelvalue',
            unique_together={('project', 'analysis_type', 'year', 'lat', 'lng')},
        ),
    ]
