# Generated by Django 5.2.1 on 2025-09-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0007_delete_beforeaftercomparison'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyzeChange',
        ),
    ]
