# Generated by Django 5.2.1 on 2025-10-31 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0007_alter_areaanalysis_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaanalysis',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='urbananalytics.project'),
        ),
    ]
