# Generated by Django 5.2.1 on 2025-09-26 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0007_rename_value_yearlypixelvalue_pixel_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyComparisonAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('area_type', models.CharField(max_length=20)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('baseline_year', models.IntegerField()),
                ('comparison_years', models.JSONField()),
                ('stats', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_comparisons', to='urbananalytics.project')),
            ],
            options={
                'unique_together': {('project', 'analysis_type', 'baseline_year', 'area_type', 'uc_name')},
            },
        ),
    ]
