# Generated by Django 5.2.1 on 2025-11-09 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0008_alter_areaanalysis_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyanalysis',
            name='kml_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='yearlyanalysis',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yearly_analyses', to='urbananalytics.project'),
        ),
    ]
