# Generated by Django 5.2.1 on 2025-10-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0008_delete_analyzechange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearlyanalysis',
            old_name='map_layer_path',
            new_name='map_id',
        ),
        migrations.AddField(
            model_name='yearlyanalysis',
            name='palette',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearlyanalysis',
            name='token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='yearlyanalysis',
            name='url_format',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
