# Generated by Django 5.2.1 on 2025-10-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0009_rename_map_layer_path_yearlyanalysis_map_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearlyanalysis',
            old_name='map_id',
            new_name='map_layer_path',
        ),
        migrations.RemoveField(
            model_name='yearlyanalysis',
            name='palette',
        ),
        migrations.RemoveField(
            model_name='yearlyanalysis',
            name='token',
        ),
        migrations.RemoveField(
            model_name='yearlyanalysis',
            name='url_format',
        ),
    ]
