# Generated by Django 5.2.1 on 2025-11-11 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0009_yearlyanalysis_kml_hash_alter_yearlyanalysis_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beforeafterpixelwise',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='beforeafterpixelwise',
            name='kml_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='beforeafterpixelwise',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urbananalytics.project'),
        ),
        migrations.AlterUniqueTogether(
            name='beforeafterpixelwise',
            unique_together={('project', 'analysis_type', 'area_type', 'uc_name', 'before_year', 'after_year', 'kml_hash')},
        ),
        migrations.AddIndex(
            model_name='beforeafterpixelwise',
            index=models.Index(fields=['kml_hash'], name='urbananalyt_kml_has_c282a5_idx'),
        ),
    ]
