# Generated by Django 5.2.1 on 2025-11-21 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0010_alter_beforeafterpixelwise_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapstate',
            old_name='center_coords',
            new_name='map_center',
        ),
        migrations.RemoveField(
            model_name='mapstate',
            name='active_layer',
        ),
        migrations.RemoveField(
            model_name='mapstate',
            name='basemap_style',
        ),
        migrations.RemoveField(
            model_name='mapstate',
            name='project_area',
        ),
        migrations.RemoveField(
            model_name='mapstate',
            name='toggle_state',
        ),
        migrations.AddField(
            model_name='mapstate',
            name='after_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapstate',
            name='area_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mapstate',
            name='before_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapstate',
            name='city_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapstate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapstate',
            name='kml_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='mapstate',
            name='project',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='map_state', to='urbananalytics.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapstate',
            name='selected_analysis_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mapstate',
            name='selected_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mapstate',
            name='selected_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapstate',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mapstate',
            name='zoom_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
