# Generated by Django 5.2.1 on 2025-10-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0010_rename_map_id_yearlyanalysis_map_layer_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearlyanalysis',
            name='map_layer_path',
        ),
        migrations.AddField(
            model_name='yearlyanalysis',
            name='map_layer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
