# Generated by Django 5.2.1 on 2025-10-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0011_remove_yearlyanalysis_map_layer_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearlyanalysis',
            name='map_layer_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
