# Generated by Django 5.2.1 on 2025-11-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0011_rename_center_coords_mapstate_map_center_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapstate',
            name='kml_hash',
        ),
    ]
