# Generated by Django 5.2.1 on 2025-10-01 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0012_yearlyanalysis_map_layer_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeforeAfterAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('area_type', models.CharField(max_length=20)),
                ('uc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('before_year', models.IntegerField()),
                ('after_year', models.IntegerField()),
                ('stats_before', models.JSONField(blank=True, null=True)),
                ('stats_after', models.JSONField(blank=True, null=True)),
                ('comparison', models.JSONField(blank=True, null=True)),
                ('map_layer_before_path', models.CharField(blank=True, max_length=500, null=True)),
                ('map_layer_after_path', models.CharField(blank=True, max_length=500, null=True)),
                ('map_layer_before', models.JSONField(blank=True, null=True)),
                ('map_layer_after', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='before_after_analyses', to='urbananalytics.project')),
            ],
            options={
                'unique_together': {('project', 'analysis_type', 'area_type', 'uc_name', 'before_year', 'after_year')},
            },
        ),
    ]
