# Generated by Django 5.2.1 on 2025-11-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0012_remove_mapstate_kml_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectArea',
        ),
    ]
