# Generated by Django 5.2.1 on 2025-10-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0013_beforeafteranalysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beforeafteranalysis',
            name='map_layer_after',
        ),
        migrations.RemoveField(
            model_name='beforeafteranalysis',
            name='map_layer_before',
        ),
    ]
