# Generated by Django 5.2.1 on 2025-10-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0014_remove_beforeafteranalysis_map_layer_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beforeafteranalysis',
            name='is_pixelwise',
            field=models.BooleanField(default=False),
        ),
    ]
