# Generated by Django 5.2.1 on 2025-10-02 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0016_remove_beforeafteranalysis_is_pixelwise_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaanalysis',
            options={'ordering': ['uc_name', 'start_date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='areaanalysis',
            old_name='map_layer_path',
            new_name='cog_https_url',
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='beforeafterpixelwise',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='beforeafterpixelwise',
            name='map_layer_after_path',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beforeafterpixelwise',
            name='map_layer_before_path',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('project_name', 'owner')},
        ),
        migrations.AddIndex(
            model_name='beforeafterpixelwise',
            index=models.Index(fields=['project', 'analysis_type', 'before_year', 'after_year'], name='urbananalyt_project_26906e_idx'),
        ),
        migrations.AddIndex(
            model_name='beforeafterpixelwise',
            index=models.Index(fields=['area_type'], name='urbananalyt_area_ty_9d3438_idx'),
        ),
    ]
