# Generated by Django 5.2.1 on 2025-10-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0017_alter_areaanalysis_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areaanalysis',
            old_name='cog_https_url',
            new_name='tile_url_template',
        ),
    ]
