# Generated by Django 5.2.7 on 2025-10-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0018_rename_cog_https_url_areaanalysis_tile_url_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearlyanalysis',
            options={'ordering': ['uc_name', 'year']},
        ),
        migrations.RenameField(
            model_name='yearlyanalysis',
            old_name='map_layer_path',
            new_name='tile_url_template',
        ),
        migrations.RemoveField(
            model_name='yearlyanalysis',
            name='map_layer',
        ),
    ]
