# Generated by Django 5.2.7 on 2025-10-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0019_alter_yearlyanalysis_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beforeafteranalysis',
            name='map_layer_after_path',
        ),
        migrations.RemoveField(
            model_name='beforeafteranalysis',
            name='map_layer_before_path',
        ),
    ]
