# Generated by Django 5.2.7 on 2025-10-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbananalytics', '0020_remove_beforeafteranalysis_map_layer_after_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beforeafterpixelwise',
            name='map_layer_after_path',
        ),
        migrations.RemoveField(
            model_name='beforeafterpixelwise',
            name='map_layer_before_path',
        ),
        migrations.AddField(
            model_name='beforeafterpixelwise',
            name='tile_url_after',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='beforeafterpixelwise',
            name='tile_url_before',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
